### ISSUE TITLE
Tip for form labels

### ISSUE THREAD

**Issue by marialani** [fac19/week5-DGHP#31]
If you wrap your input field in a label then you don't need the label for attribute or the input id atribute (as long as the id is only added for the label).

I always found this much easier to type out in my IDE especially later down the line when you may be creating large forms.

**Comment by oliverjam** [comment]
One caveat to this top tip: Dragon Naturally Speaking (an assistive technology for voice controlling a computer) doesn't recognise this type of label and requires a `for` attribute :(

https://adrianroselli.com/2020/01/my-priority-of-methods-for-labeling-a-control.html#HTML

There is a lot of inconsistency in the assistive tech world, it's super annoying
